export type SupportedLanguage = 'en' | 'tr' | 'es' | 'de' | 'fr';

export const translations = {
    en: {
        settings_language: "Language",
        settings_language_desc: "Select the plugin language.",
        settings_api_key: "Gemini API Key",
        settings_api_key_desc: "Get your API key from Google AI Studio.",
        settings_model: "Model",
        settings_model_desc: "Select the Gemini model to use.",
        ai_suggestions_title: "Quick start",
        ai_suggestions_hint: "Pick an action, then edit and send it.",
        ai_suggestion_youtube_analysis: "Analyze YouTube video",
        ai_suggestion_summarize: "Summarize text",
        ai_suggestion_explain_code: "Explain code",
        ai_suggestion_fix_grammar: "Fix grammar",
        ai_suggestion_translate: "Translate",
        ai_suggestion_brainstorm: "Brainstorm ideas",
        ai_suggestion_professional_tone: "Professional tone",
        ai_suggestion_extract_keywords: "Extract keywords",
        ai_suggestion_continue_writing: "Continue writing",
        ai_suggestion_create_table: "Create a table",
        chat_placeholder: "Talk to Kai...",
        chat_welcome: "Hello! I am Kai. How can I help you today? (Past conversations are in the clock icon at the bottom left)",
        chat_thinking: "Kai is thinking...",
        history_cleared_msg: "Context cleared. Ready to talk on a new note!",
        history_cleared_notice: "Kai: History cleared.",
        file_error: "Could not read file.",
        error_occurred: "An error occurred.",
        operation_success: "Operation completed successfully.",
        notice_appended: "Kai added text to your note.",
        notice_rewritten: "Kai rewrote your note.",
        notice_created: "Kai created a new note: {0}",
        api_missing: "Please enter your Gemini API key in settings.",
        menu_chat: "Kai: Chat about selection",
        menu_explain: "Kai: Explain",
        menu_fix: "Kai: Fix grammar",
        menu_summarize: "Kai: Summarize",
        menu_translate: "Kai: Translate (TR/EN)",
        btn_copy: "Copy",
        btn_edit: "Edit",
        btn_sources: "Web Sources",
        btn_short: "Short",
        btn_medium: "Medium",
        btn_long: "Long",
        modal_options_title: "AI Options",
        modal_options_length: "Response length",
        modal_options_tone: "Tone",
        modal_options_task: "Task",
        modal_options_style: "Style",
        modal_options_format: "Output format",
        task_general: "General",
        task_summarize: "Summarize",
        task_rewrite: "Rewrite",
        task_explain: "Explain",
        task_translate: "Translate",
        task_brainstorm: "Brainstorm",
        style_balanced: "Balanced",
        style_brief: "Brief",
        style_detailed: "Detailed",
        style_creative: "Creative",
        msg_copied: "Copied to clipboard",
        modal_sources_title: "Information Sources"
    },
    tr: {
        settings_language: "Dil",
        settings_language_desc: "Eklenti dilini seçin.",
        settings_api_key: "Gemini API Anahtarı",
        settings_api_key_desc: "Google AI Studio'dan API anahtarınızı alın.",
        settings_model: "Model",
        settings_model_desc: "Kullanılacak Gemini modelini seçin.",
        ai_suggestions_title: "Hızlı başlangıç",
        ai_suggestions_hint: "Bir eylem seçin, sonra düzenleyip gönderin.",
        ai_suggestion_youtube_analysis: "YouTube videosunu analiz et",
        ai_suggestion_summarize: "Metni özetle",
        ai_suggestion_explain_code: "Kodu açıkla",
        ai_suggestion_fix_grammar: "Yazım hatalarını düzelt",
        ai_suggestion_translate: "Çevir",
        ai_suggestion_brainstorm: "Fikir üret",
        ai_suggestion_professional_tone: "Profesyonel ton",
        ai_suggestion_extract_keywords: "Anahtar kelimeleri çıkar",
        ai_suggestion_continue_writing: "Devamını yaz",
        ai_suggestion_create_table: "Tablo oluştur",
        chat_placeholder: "Kai ile konuş...",
        chat_welcome: "Merhaba! Ben Kai. Bugün sana nasıl yardımcı olabilirim? (Geçmiş konuşmalar sol alttaki saat ikonunda)",
        chat_thinking: "Kai düşünüyor...",
        history_cleared_msg: "Bağlam sıfırlandı. Yeni not üzerinde konuşmaya hazırız!",
        history_cleared_notice: "Kai: Geçmiş temizlendi.",
        file_error: "Dosya okunamadı.",
        error_occurred: "Bir hata oluştu.",
        operation_success: "İşlem başarıyla tamamlandı.",
        notice_appended: "Kai notunuza ekleme yaptı.",
        notice_rewritten: "Kai notunuzu baştan yazdı.",
        notice_created: "Kai yeni not oluşturdu: {0}",
        api_missing: "Lütfen ayarlardan Gemini API anahtarını girin.",
        menu_chat: "Kai: Seçim Hakkında Sohbet Et",
        menu_explain: "Kai: Seçimi Açıkla",
        menu_fix: "Kai: Seçimi Düzelt",
        menu_summarize: "Kai: Seçimi Özetle",
        menu_translate: "Kai: Çevir (TR/EN)",
        btn_copy: "Kopyala",
        btn_edit: "Düzenle",
        btn_sources: "Kaynaklar",
        btn_short: "Kısa",
        btn_medium: "Orta",
        btn_long: "Detaylı",
        modal_options_title: "AI Seçenekleri",
        modal_options_length: "Yanıt uzunluğu",
        modal_options_tone: "Ton",
        modal_options_task: "Görev",
        modal_options_style: "Stil",
        modal_options_format: "Çıktı formatı",
        task_general: "Genel",
        task_summarize: "Özetle",
        task_rewrite: "Düzenle",
        task_explain: "Açıkla",
        task_translate: "Çevir",
        task_brainstorm: "Fikir üret",
        style_balanced: "Dengeli",
        style_brief: "Kısa",
        style_detailed: "Detaylı",
        style_creative: "Yaratıcı",
        msg_copied: "Panoya kopyalandı",
        modal_sources_title: "İnternet Kaynakları"
    },
    es: {
        settings_language: "Idioma",
        settings_language_desc: "Seleccione el idioma del plugin.",
        settings_api_key: "Clave API de Gemini",
        settings_api_key_desc: "Obtenga su clave API de Google AI Studio.",
        settings_model: "Modelo",
        settings_model_desc: "Seleccione el modelo de Gemini a utilizar.",
        chat_placeholder: "Habla con Kai...",
        chat_welcome: "¡Hola! Soy Kai. ¿Cómo puedo ayudarte hoy? (Las conversaciones pasadas están en el icono del reloj abajo a la izquierda)",
        chat_thinking: "Kai está pensando...",
        history_cleared_msg: "Contexto borrado. ¡Listos para hablar sobre una nota nueva!",
        history_cleared_notice: "Kai: Historial borrado.",
        file_error: "No se pudo leer el archivo.",
        error_occurred: "Ocurrió un error.",
        operation_success: "Operación completada con éxito.",
        notice_appended: "Kai añadió texto a tu nota.",
        notice_rewritten: "Kai reescribió tu nota.",
        notice_created: "Kai creó una nueva nota: {0}",
        api_missing: "Por favor, introduzca su clave API de Gemini en la configuración."
    },
    de: {
        settings_language: "Sprache",
        settings_language_desc: "Wählen Sie die Plugin-Sprache.",
        settings_api_key: "Gemini API-Schlüssel",
        settings_api_key_desc: "Holen Sie sich Ihren API-Schlüssel von Google AI Studio.",
        settings_model: "Modell",
        settings_model_desc: "Wählen Sie das zu verwendende Gemini-Modell.",
        chat_placeholder: "Sprich mit Kai...",
        chat_welcome: "Hallo! Ich bin Kai. Wie kann ich dir heute helfen? (Vergangene Unterhaltungen findest du im Uhrensymbol unten links)",
        chat_thinking: "Kai denkt nach...",
        history_cleared_msg: "Kontext gelöscht. Bereit, über eine neue Notiz zu sprechen!",
        history_cleared_notice: "Kai: Verlauf gelöscht.",
        file_error: "Datei konnte nicht gelesen werden.",
        error_occurred: "Ein Fehler ist aufgetreten.",
        operation_success: "Vorgang erfolgreich abgeschlossen.",
        notice_appended: "Kai hat Text zu deiner Notiz hinzugefügt.",
        notice_rewritten: "Kai hat deine Notiz neu geschrieben.",
        notice_created: "Kai hat eine neue Notiz erstellt: {0}",
        api_missing: "Bitte geben Sie Ihren Gemini API-Schlüssel in den Einstellungen ein.",
        btn_short: "Kurz",
        btn_medium: "Mittel",
        btn_long: "Lang",
    },
    fr: {
        settings_language: "Langue",
        settings_language_desc: "Sélectionnez la langue du plugin.",
        settings_api_key: "Clé API Gemini",
        settings_api_key_desc: "Obtenez votre clé API depuis Google AI Studio.",
        settings_model: "Modèle",
        settings_model_desc: "Sélectionnez le modèle Gemini à utiliser.",
        chat_placeholder: "Parlez à Kai...",
        chat_welcome: "Bonjour ! Je suis Kai. Comment puis-je vous aider aujourd'hui ? (Les conversations passées se trouvent dans l'icône d'horloge en bas à gauche)",
        chat_thinking: "Kai réfléchit...",
        history_cleared_msg: "Contexte effacé. Prêt à parler d'une nouvelle note !",
        history_cleared_notice: "Kai : Historique effacé.",
        file_error: "Impossible de lire le fichier.",
        error_occurred: "Une erreur s'est produite.",
        operation_success: "Opération terminée avec succès.",
        notice_appended: "Kai a ajouté du texte à votre note.",
        notice_rewritten: "Kai a réécrit votre note.",
        notice_created: "Kai a créé une nouvelle note : {0}",
        api_missing: "Veuillez entrer votre clé API Gemini dans les paramètres.",
        btn_short: "Court",
        btn_medium: "Moyen",
        btn_long: "Long",
    }
};

type TranslationKey = keyof typeof translations.en;
type TranslationMap = Record<TranslationKey, string>;

let currentLanguage: SupportedLanguage = 'en'; // Default language

export const setLanguage = (lang: SupportedLanguage) => {
    currentLanguage = lang;
};

export const t = (key: TranslationKey, ...args: string[]): string => {
    const selectedLocale = translations[currentLanguage] as TranslationMap | undefined;
    let text = selectedLocale?.[key] ?? translations.en[key] ?? key;
    args.forEach((arg, index) => {
        text = text.replace(`{${index}}`, arg);
    });
    return text;
};